<a href="https://colab.research.google.com/github/Murali-Krishna22ds/December2025GenAI/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
data=np.random.randint(0,100,(5,5))
data

array([[59, 68, 57, 96, 99],
       [82, 89, 81, 59, 46],
       [77, 50, 95, 32, 89],
       [96,  6, 67, 84, 26],
       [47,  5, 57, 72, 63]])

In [ ]:
type(np.array([1,2,3]))

numpy.ndarray

In [ ]:
data

array([[59, 68, 57, 96, 99],
       [82, 89, 81, 59, 46],
       [77, 50, 95, 32, 89],
       [96,  6, 67, 84, 26],
       [47,  5, 57, 72, 63]])

In [ ]:
data[0,0]

np.int64(59)

In [ ]:
data[-3:-1,-3:-1]

array([[95, 32],
       [67, 84]])

In [ ]:
data[-2:-1,-2:-1]

array([[84]])

In [ ]:
x=[1,2,3]
print(type(x))
y=(np.array([1,2,3]))
type(y)

<class 'list'>


numpy.ndarray

In [ ]:
x/2

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [ ]:
y/2

array([0.5, 1. , 1.5])

In [ ]:
x=[1,2,3,6.0]
y=np.array([1,2,3,6.0])
print(x)
print(y)

[1, 2, 3, 6.0]
[1. 2. 3. 6.]


In [ ]:
x=[1,2,3,6.0,"data"]
y=np.array([1,2,3,6.0,"data"])
print(x)
y

[1, 2, 3, 6.0, 'data']


array(['1', '2', '3', '6.0', 'data'], dtype='<U32')

In [ ]:
#list is heterogenous
#numpy is homogenous


1. due to different data type you can't perform operations on list whereas numpy you can perform operations.
2. we can store different data types whereas in numpy it is based on the order  "i<float<str".
3. numpy is memory efficient due to same data type whereas list is less efficient.


In [ ]:
#Random family func

In [ ]:
np.random.randint(0,100,(5,5))

array([[90,  5, 99,  7, 52],
       [84, 60,  4, 42, 23],
       [19, 51,  5, 46, 45],
       [58, 17, 14, 92, 61],
       [ 7, 26, 65, 42, 37]])

In [ ]:
np.random.rand(3,3) #values r 0 to 1

array([[0.21175139, 0.78457985, 0.11753083],
       [0.82790545, 0.14140526, 0.52416291],
       [0.72973801, 0.86985794, 0.60510044]])

In [ ]:
data=np.array([1,2,3,4])
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [ ]:
(data-data.min())/(data.max()-data.min())

array([0.        , 0.33333333, 0.66666667, 1.        ])

## Normalization of the data refers to all the variables should be on the same scale